Module bbTimers
    Public AddLineToStreamTime As New bbTimer("Add Line To Stream")
    Public FindPlottingPointTime As New bbTimer("Find Plotting Point")
    Public StaffLineTime As New bbTimer("Staff Lines and Frame")
    Public NotesTime As New bbTimer("Notes")
    Public DrawNoteWithStemTime As New bbTimer("Draw Note With Stem Time")
    Public TotalTime As New bbTimer("Total Time")
    Public DrawQuarterNoteTime As New bbTimer("Draw Quarter Note Time")
    Public TestTime1 As New bbTimer("Test Time 1")
    Public TestTime2 As New bbTimer("Test Time 2")
    Public TestTime3 As New bbTimer("Test Time 3")
    Public TestTime4 As New bbTimer("Test Time 4")
    Public TestTime5 As New bbTimer("Test Time 5")
    Public TestTime6 As New bbTimer("Test Time 6")

    Public Sub PrintAllTimers()
        AddLineToStreamTime.DebugOut(TotalTime.ElapsedTime)
        FindPlottingPointTime.DebugOut(TotalTime.ElapsedTime)
        StaffLineTime.DebugOut(TotalTime.ElapsedTime)
        NotesTime.DebugOut(TotalTime.ElapsedTime)
        DrawNoteWithStemTime.DebugOut(TotalTime.ElapsedTime)
        DrawQuarterNoteTime.DebugOut(TotalTime.ElapsedTime)
        TestTime1.DebugOut(TotalTime.ElapsedTime)
        TestTime2.DebugOut(TotalTime.ElapsedTime)
        TestTime3.DebugOut(TotalTime.ElapsedTime)
        TestTime4.DebugOut(TotalTime.ElapsedTime)
        TestTime5.DebugOut(TotalTime.ElapsedTime)
        TestTime6.DebugOut(TotalTime.ElapsedTime)
        TotalTime.DebugOut(TotalTime.ElapsedTime)
    End Sub
End Module
